[package]
name = "zlock"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.102"
libc = "0.2.153"
pam = "0.8.0"
xcb = { version = "1.7.0", features = ["as-raw-xcb-connection"] }
xkbcommon = { version = "0.9.0", features = ["x11"] }
